import Head from 'next/head'
import Type from '../models/whyUs';
import {FC} from "react";
import { GetStaticProps } from 'next';

import Header from '../containers/header';
import IntroduceOurself from '../containers/introduceOurself';
import WhyUs from '../containers/whyUs';
import AreaOfPractice from '../containers/areaOfPractice';
import Footer from '../containers/footer';

  type Props = {
    whyUs :Type[]
  }

  const Home :FC<Props> = (props) => {
    return (
      <>
        <Head>
          <title>Maquette</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Header/>
          <IntroduceOurself/>
          <WhyUs whyUs={props.whyUs}/>
          <AreaOfPractice/>
          <Footer/>
        </div>
      </>
    )
}

export const getStaticProps :GetStaticProps = async () => {

  const result = await fetch("http://localhost:3000/api/whyUsData");
  const data = await result.json();

  return ({
      props: {
          whyUs: data
      },
      revalidate: 1
  });
}

export default Home;